### PR TITLE
Support direct messages to external bots

### PR DESCRIPTION
**Pull request by hpeebles**

### CODE REVIEW

**Review by julianjelfs — COMMENTED** [review]
Maybe this is just a naming issue, but a `readonlyChat` property on a _user_ makes no sense to me.

**Comment by hpeebles** [comment]
> Maybe this is just a naming issue, but a `readonlyChat` property on a _user_ makes no sense to me.

Yeah I didn't really like that either. Maybe something like `acceptsDirectMessages` is better?

**Comment by hpeebles** [comment]
I felt `readonly` on its own wasn't very clear, and on the UI we say 'This chat is read-only' which is why I went with 'readonlyChat'.

**Comment by julianjelfs** [comment]
> > Maybe this is just a naming issue, but a `readonlyChat` property on a _user_ makes no sense to me.
> 
> 
> 
> Yeah I didn't really like that either. Maybe something like `acceptsDirectMessages` or `canMessage` is better?

It's not _just_ the name either. The typing seems a bit loose. It seems like a User should be a union type and this property only exists in the BotUser branch.

**Review by julianjelfs — APPROVED** [review]

**Pull request merged**
