### PR TITLE
Add "claim_prize" to group inspect_message

### PR DESCRIPTION
**Pull request by megrogan**

### CODE REVIEW

**Review by hpeebles — DISMISSED** [review]

**Comment by Deanspot** [comment]
Add "claim_prize" to group
inspect_message

**Comment by gunguu2020** [comment]
Add claim prize

**Comment by Optimismeth** [comment]
Add claim_prize

**Comment by jeriko2075** [comment]
claim_prize

**Comment by Walintin1** [comment]
Add "claim_prize

**Pull request merged**
